name: Send Email on Issue Assignment
'on':
  issues:
    types:
      - assigned
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mail command
        run: sudo apt-get update && sudo apt-get install -y mailutils
      - name: Send email
        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          EMAIL_USERNAME: '${{ secrets.EMAIL_USERNAME }}'
          EMAIL_PASSWORD: '${{ secrets.EMAIL_PASSWORD }}'
          RECIPIENT_EMAIL: '${{ github.event.issue.assignee.email }}'
        run: >
          echo "Subject: New Issue Assigned: ${{ github.event.issue.title }}" >
          email.txt

          echo "" >> email.txt

          echo "Hello," >> email.txt

          echo "" >> email.txt

          echo "You have been assigned to the following issue:" >> email.txt

          echo "" >> email.txt

          echo "Title: ${{ github.event.issue.title }}" >> email.txt

          echo "URL: ${{ github.event.issue.html_url }}" >> email.txt

          echo "" >> email.txt

          echo "Best regards, Luc" >> email.txt

          echo "Your GitHub Actions" >> email.txt

          cat email.txt | sendmail -t
