name: Send email to assigned user on new issue

on:
  issues:
    types: [assigned]

jobs:
  send_email:
    runs-on: windows-latest

    steps:
    - name: Map GitHub username to email
      id: map_email
      run: |
        # Replace with your actual mappings
        declare -A email_map
        email_map["githubuser1"]="paulaivanovic6@gmail.com"
        email_map["githubuser2"]="joviclucia10@gmail.com"
        email_map["githubuser3"]="mia.zuvic1234@gmail.com"
        email_map["githubuser4"]="nikabazon2002@gmail.com"
        # email_map["githubuser5"]="user5@example.com"
        # email_map["githubuser6"]="user6@example.com"
        
        assignee=${{ github.event.issue.assignee.login }}
        email=${email_map[$assignee]}
        
        if [ -z "$email" ]; then
          echo "No email found for the user: $assignee"
          exit 1
        fi
        
        echo "::set-output name=email::$email"
      
    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: ${{ secrets.EMAIL_USERNAME }}  # Koristimo username kao sender email adresu
        subject: New issue assigned to you
        body: |
          Hello,

          Your colleagues have a new assignment for you!
          Enjoy the work. :)

          Issue Title: ${{ github.event.issue.title }}
          Issue URL: ${{ github.event.issue.html_url }}

          Regards,
          Your GitHub Action
        to: ${{ steps.map_email.outputs.email }}
