name: Send email to assigned user on new issue

on:
  issues:
    types: [assigned]

jobs:
  send_email:
    runs-on: windows-latest

    steps:
    - name: Debug assignee
      run: echo "Assignee: ${{ github.event.issue.assignee.login }}"

    - name: Map GitHub username to email
      id: map_email
      run: |
        # Zamijeni s stvarnim korisničkim imenima i email adresama
        declare -A email_map
        email_map["PaulaIvanovic"]="paulaivanovic6@gmail.com"
        email_map["ljovic"]="joviclucia10@gmail.com"
        email_map["Mia2404"]="mia.zuvic1234@gmail.com"
        email_map["bazon8e82"]="nikabazon2002@gmail.com"
        email_map["githubuser5"]="user5@example.com"
        email_map["githubuser6"]="user6@example.com"
        
        assignee="${{ github.event.issue.assignee.login }}"
        echo "Assignee: $assignee"
        
        email="${email_map[$assignee]}"
        echo "Mapped email: $email"
        
        if [ -z "$email" ]; then
          echo "No email found for the user: $assignee"
          exit 1
        fi
        
        echo "::set-output name=email::$email"

    - name: Debug mapped email
      run: echo "Mapped email is ${{ steps.map_email.outputs.email }}"

    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: ${{ secrets.EMAIL_USERNAME }}
        to: ${{ steps.map_email.outputs.email }}
        subject: New issue assigned to you
        body: |
          Hello,

          Your colleagues have a new assignment for you!
          Enjoy the work. :)

          Issue Title: ${{ github.event.issue.title }}
          Issue URL: ${{ github.event.issue.html_url }}

          Regards,
          Your GitHub Action
