name: Send Email on Issue Assignment

on:
  issues:
    types: [assigned]

jobs:
  notify-assigned:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install smtplib
        run: pip install smtplib

      - name: Send email
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        run: |
          python - <<EOF
          import os
          import smtplib
          from email.message import EmailMessage

          # Setup the SMTP server connection
          smtp_server = '${{ secrets.SMTP_SERVER }}'
          smtp_port = int('${{ secrets.SMTP_PORT }}')
          smtp_username = '${{ secrets.SMTP_USERNAME }}'
          smtp_password = '${{ secrets.SMTP_PASSWORD }}'
          recipient_emails = '${{ secrets.RECIPIENT_EMAILS }}'.splitlines()

          msg = EmailMessage()
          msg.set_content('Your colleagues have an issue for you. Enjoy coding!')
          msg['Subject'] = 'Issue Assigned Notification'
          msg['From'] = smtp_username

          # Determine the recipient based on the assignee
          assignee_email = os.getenv('ISSUE_ASSIGNEE_EMAIL')  # This needs to be fetched from the issue event payload
          recipient_email = None
          for email in recipient_emails:
              if email == assignee_email:
                  recipient_email = email
                  break

          if recipient_email:
              msg['To'] = recipient_email
              # Connect to the SMTP server and send the email
              server = smtplib.SMTP(smtp_server, smtp_port)
              server.starttls()
              server.login(smtp_username, smtp_password)
              server.send_message(msg)
              server.quit()

              print(f"Email sent successfully to {recipient_email}.")
          else:
              print("No matching recipient found.")

          EOF
