name: Send Email on Issue Assignment

on:
  issues:
    types: [assigned]

jobs:
  notify-assigned:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install smtplib
        run: pip install smtplib

      - name: Send email
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_USERNAMES: ${{ secrets.RECIPIENT_USERNAMES }} # Store GitHub usernames as a comma-separated string
        run: |
          python - <<EOF
          import os
          import smtplib
          from email.message import EmailMessage
          import json

          # Setup the SMTP server connection
          smtp_server = '${{ secrets.SMTP_SERVER }}'
          smtp_port = int('${{ secrets.SMTP_PORT }}')
          smtp_username = '${{ secrets.SMTP_USERNAME }}'
          smtp_password = '${{ secrets.SMTP_PASSWORD }}'
          recipient_usernames = '${{ secrets.RECIPIENT_USERNAMES }}'.split(',')

          msg = EmailMessage()
          msg.set_content('Your colleagues have an issue for you. Enjoy coding!')
          msg['Subject'] = 'Issue Assigned Notification'
          msg['From'] = smtp_username

          # Retrieve the assignee's login name from the GitHub context
          payload = json.loads(os.environ["GITHUB_EVENT"])
          assignee_login = payload.get("issue", {}).get("assignees", [{}])[0].get("login")

          recipient_email = None
          for username in recipient_usernames:
              if username == assignee_login:
                  recipient_email = f'{username}@yourdomain.com'  # Replace @yourdomain.com with the domain you use for email addresses
                  break

          if recipient_email:
              msg['To'] = recipient_email
              # Connect to the SMTP server and send the email
              server = smtplib.SMTP(smtp_server, smtp_port)
              server.starttls()
              server.login(smtp_username, smtp_password)
              server.send_message(msg)
              server.quit()

              print(f"Email sent successfully to {recipient_email}.")
          else:
              print("No matching recipient found.")

          EOF
